name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      aquaURL:
        description: 'URL'
        required: true
        default: 'https://app.aqua-cloud.io/aquaWebNG'
        type: string
      aquaUser:
        description: 'aquaUser'
        required: true
        default: '*'
        type: string
      aquaPassword:
        description: 'aquaPassword'
        required: true
        default: '*'
        type: string

env:
  AQUA_URL: ${{ github.event.inputs.aquaURL || 'https://app.aqua-cloud.io/aquaWebNG' }}
  AQUA_USERNAME: ${{ github.event.inputs.aquaUser }}
  AQUA_PASSWORD: ${{ github.event.inputs.aquaPassword }}

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inject env variables
        run: |
          echo ${{ env.AQUA_URL }}
          echo ${{ env.AQUA_USERNAME }}
          echo ${{ env.AQUA_PASSWORD }}
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
